[build]
  command = "npm run build"
  publish = "dist"

# API proxy (EZ KELL NEKED)
[[redirects]]
  from = "/users/*"
  to = "https://nodejs308.dszcbaross.edu.hu/users/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/orders/*"
  to = "https://nodejs308.dszcbaross.edu.hu/orders/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/products/*"
  to = "https://nodejs308.dszcbaross.edu.hu/products/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/tervezo/*"
  to = "https://nodejs308.dszcbaross.edu.hu/tervezo/:splat"
  status = 200
  force = true

# SPA fallback (EZ MARAD ALUL!)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200